In [127]:
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen

In [128]:
req = Request('https://in.investing.com/equities/itc-company-profile'
                , headers={'User-Agent': 'Mozilla/5.0'})

In [129]:
pages = urlopen(req).read()

In [130]:
soup = BeautifulSoup(pages.decode('utf-8'),'html.parser')

In [131]:
list_value = list(soup.children)

In [132]:
html_page = list_value[3]

In [133]:
html_body=list(html_page.children)[3]

In [134]:
html_body.findAllNext('h2',class_='section-title')[0].get_text().strip()

'ITC Ltd Company Profile'

In [135]:
dic = dict()

In [136]:
dic['Company'] = html_body.findAllNext('h2',class_='section-title')[0].get_text().strip()

In [137]:
profile_details = html_body.findAllNext('dl',class_='profile-details-list')[0]
anchor = profile_details.findAllNext('a',class_='common-link')

In [138]:
 dic['Industry'] = anchor[0].get_text()

In [139]:
 dic['Sector'] = anchor[1].get_text()

In [140]:
 dic['Employees'] =profile_details.findAllNext('dd',class_='profile-details-details')[2].get_text().strip()

In [141]:
 dic['Equity Type'] = profile_details.findAllNext('dd',class_='profile-details-details')[3].get_text().strip()

In [142]:
dic

{'Company': 'ITC Ltd Company Profile',
 'Industry': 'Tobacco',
 'Sector': 'Consumer/Non-Cyclical',
 'Employees': '27279',
 'Equity Type': 'ORD'}

In [143]:
brief_details = html_body.findAllNext('span', class_='text common-pre-text')[0].get_text()

In [144]:
dic['Company Details'] = brief_details

In [145]:
dic

{'Company': 'ITC Ltd Company Profile',
 'Industry': 'Tobacco',
 'Sector': 'Consumer/Non-Cyclical',
 'Employees': '27279',
 'Equity Type': 'ORD',
 'Company Details': 'ITC Limited is a holding company, which is engaged in the marketing of fast moving consumer goods (FMGC). The Company operates through four segments: FMCG; Hotels; Paperboards, Paper and Packaging, and Agri Business. The FMCG segment includes Cigarettes, such as cigarettes and cigars, and Others, such as branded packaged foods businesses (Staples, Snacks and Meals; Dairy and Beverages, and Confections); Apparel; Education and Stationery Products; Personal Care Products; Safety Matches, and Agarbattis. Its Hotels segment includes Hoteliering. Its Paperboards, Paper and Packaging segment includes paperboards; paper, including specialty paper, and packaging, including flexibles. Its Agri Business segment includes Agri commodities, such as soya, spices, coffee and leaf tobacco. Its brands include Aashirvaad, Sunfeast Dark Fantasy, Bingo!, Yumitos, YiPPee!, Candyman, GumOn, Classmate, Fiama Di Wills, Vivel, Superia, Engage, Wills Lifestyle, John Players, Mangaldeep and Aim, among others.'}

In [146]:
table = html_body.findAllNext('table', class_='common-table e-executive')

In [147]:
rows = table[0].findAll('tbody')[0].findAll('tr')

In [148]:
rows

[<tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Meera Shankar</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">68</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2012</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Nirupama Rao</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">68</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2016</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Sahibzada Syed Habib-ur-Rehman</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">75</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2012</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Sunil Behari Mathur</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">74</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2005</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Shilabhadra Banerjee</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">70</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2014</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Arun Kumar Duggal</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">73</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2014</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Ajit Kumar Seth</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">67</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2019</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Additional Independent Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">David Robert Simpson</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">62</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2017</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Director - Representative of Tobacco Manufacturers (India) Limited</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">John Pulinthanam</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">59</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2018</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Non-Executive Director - Representing the General Insurers (public Sector) Association of India</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Hemant Bhargava</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">59</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2018</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Additional Non-Executive Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">S. Sivakumar</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">58</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2016</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Group Head - Agri Business</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Sanjay K. Singh</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">62</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2017</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Group Head - Paper &amp; Packaging and Divisional Chief Executive</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Rajendra Kumar Singhi</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">54</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2018</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Executive Vice President, Secretary</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">A. K. Rajput</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">63</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">0000</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Senior Vice President - Corporate Affairs</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Kannadiputhur Sundararaman Suresh</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">59</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2009</span>
 </td>
 <td class="col-officer_title">
 <span class="text">General Counsel</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Nakul Anand</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">62</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2011</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Executive Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Chitranjan Dar</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">63</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2015</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Group Head - LS&amp;T, Central Projects, EHS and Quality Assurance</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">B. Sumant</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">55</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2018</span>
 </td>
 <td class="col-officer_title">
 <span class="text">President - FMCG Businesses, Additional Wholetime Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Sanjiv Puri</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">56</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2019</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Chairman of the Board, Managing Director, Executive Director</span>
 </td>
 </tr>, <tr class="common-table-item">
 <td class="col-officer_name">
 <span class="text">Rajiv Tandon</span>
 </td>
 <td class="col-officer_age u-txt-align-end u-txt-align-end">
 <span class="text">65</span>
 </td>
 <td class="col-officer_since u-txt-align-end u-txt-align-end">
 <span class="text">2016</span>
 </td>
 <td class="col-officer_title">
 <span class="text">Chief Financial Officer, Executive Director</span>
 </td>
 </tr>]

In [149]:
rows[0].findAll('span')

[<span class="text">Meera Shankar</span>,
 <span class="text">68</span>,
 <span class="text">2012</span>,
 <span class="text">Non-Executive Independent Director</span>]

In [150]:
list_collection = list()
for row in rows:
    span_list = row.findAll('span')
    dic_executive = dict()
    dic_executive['Name']=span_list[0].get_text()
    dic_executive['Age']=span_list[1].get_text()
    dic_executive['Since']=span_list[2].get_text()
    dic_executive['Title']=span_list[3].get_text()
    list_collection.append(dic_executive)
    dic_executive = None

In [152]:
list_collection

[{'Name': 'Meera Shankar',
  'Age': '68',
  'Since': '2012',
  'Title': 'Non-Executive Independent Director'},
 {'Name': 'Nirupama Rao',
  'Age': '68',
  'Since': '2016',
  'Title': 'Non-Executive Independent Director'},
 {'Name': 'Sahibzada Syed Habib-ur-Rehman',
  'Age': '75',
  'Since': '2012',
  'Title': 'Non-Executive Independent Director'},
 {'Name': 'Sunil Behari Mathur',
  'Age': '74',
  'Since': '2005',
  'Title': 'Non-Executive Independent Director'},
 {'Name': 'Shilabhadra Banerjee',
  'Age': '70',
  'Since': '2014',
  'Title': 'Non-Executive Independent Director'},
 {'Name': 'Arun Kumar Duggal',
  'Age': '73',
  'Since': '2014',
  'Title': 'Non-Executive Independent Director'},
 {'Name': 'Ajit Kumar Seth',
  'Age': '67',
  'Since': '2019',
  'Title': 'Additional Independent Director'},
 {'Name': 'David Robert Simpson',
  'Age': '62',
  'Since': '2017',
  'Title': 'Non-Executive Director - Representative of Tobacco Manufacturers (India) Limited'},
 {'Name': 'John Pulinthanam',
  'Age': '59',
  'Since': '2018',
  'Title': 'Non-Executive Director - Representing the General Insurers (public Sector) Association of India'},
 {'Name': 'Hemant Bhargava',
  'Age': '59',
  'Since': '2018',
  'Title': 'Additional Non-Executive Director'},
 {'Name': 'S. Sivakumar',
  'Age': '58',
  'Since': '2016',
  'Title': 'Group Head - Agri Business'},
 {'Name': 'Sanjay K. Singh',
  'Age': '62',
  'Since': '2017',
  'Title': 'Group Head - Paper & Packaging and Divisional Chief Executive'},
 {'Name': 'Rajendra Kumar Singhi',
  'Age': '54',
  'Since': '2018',
  'Title': 'Executive Vice President, Secretary'},
 {'Name': 'A. K. Rajput',
  'Age': '63',
  'Since': '0000',
  'Title': 'Senior Vice President - Corporate Affairs'},
 {'Name': 'Kannadiputhur Sundararaman Suresh',
  'Age': '59',
  'Since': '2009',
  'Title': 'General Counsel'},
 {'Name': 'Nakul Anand',
  'Age': '62',
  'Since': '2011',
  'Title': 'Executive Director'},
 {'Name': 'Chitranjan Dar',
  'Age': '63',
  'Since': '2015',
  'Title': 'Group Head - LS&T, Central Projects, EHS and Quality Assurance'},
 {'Name': 'B. Sumant',
  'Age': '55',
  'Since': '2018',
  'Title': 'President - FMCG Businesses, Additional Wholetime Director'},
 {'Name': 'Sanjiv Puri',
  'Age': '56',
  'Since': '2019',
  'Title': 'Chairman of the Board, Managing Director, Executive Director'},
 {'Name': 'Rajiv Tandon',
  'Age': '65',
  'Since': '2016',
  'Title': 'Chief Financial Officer, Executive Director'}]

In [154]:
import pandas as pd
data_frame = pd.DataFrame([dic])

In [167]:
data_frame

,Company,Industry,Sector,Employees,Equity Type,Company Details
0,ITC Ltd Company Profile,Tobacco,Consumer/Non-Cyclical,27279,ORD,"ITC Limited is a holding company, which is eng..."

In [168]:
top_executive = pd.DataFrame(list_collection)

In [169]:
top_executive

,Name,Age,Since,Title
0,Meera Shankar,68,2012,Non-Executive Independent Director
1,Nirupama Rao,68,2016,Non-Executive Independent Director
2,Sahibzada Syed Habib-ur-Rehman,75,2012,Non-Executive Independent Director
3,Sunil Behari Mathur,74,2005,Non-Executive Independent Director
4,Shilabhadra Banerjee,70,2014,Non-Executive Independent Director
5,Arun Kumar Duggal,73,2014,Non-Executive Independent Director
6,Ajit Kumar Seth,67,2019,Additional Independent Director
7,David Robert Simpson,62,2017,Non-Executive Director - Representative of Tob...
8,John Pulinthanam,59,2018,Non-Executive Director - Representing the Gene...
9,Hemant Bhargava,59,2018,Additional Non-Executive Director
10,S. Sivakumar,58,2016,Group Head - Agri Business
11,Sanjay K. Singh,62,2017,Group Head - Paper & Packaging and Divisional ...
12,Rajendra Kumar Singhi,54,2018,"Executive Vice President, Secretary"
13,A. K. Rajput,63,0000,Senior Vice President - Corporate Affairs
14,Kannadiputhur Sundararaman Suresh,59,2009,General Counsel
15,Nakul Anand,62,2011,Executive Director
16,Chitranjan Dar,63,2015,"Group Head - LS&T, Central Projects, EHS and Q..."
17,B. Sumant,55,2018,"President - FMCG Businesses, Additional Wholet..."
18,Sanjiv Puri,56,2019,"Chairman of the Board, Managing Director, Exec..."
19,Rajiv Tandon,65,2016,"Chief Financial Officer, Executive Director"

In [170]:
final_data = pd.concat([data_frame,top_executive ], axis=1)

In [171]:
final_data

,Company,Industry,Sector,Employees,Equity Type,Company Details,Name,Age,Since,Title
0,ITC Ltd Company Profile,Tobacco,Consumer/Non-Cyclical,27279,ORD,"ITC Limited is a holding company, which is eng...",Meera Shankar,68,2012,Non-Executive Independent Director
1,NaN,NaN,NaN,NaN,NaN,NaN,Nirupama Rao,68,2016,Non-Executive Independent Director
2,NaN,NaN,NaN,NaN,NaN,NaN,Sahibzada Syed Habib-ur-Rehman,75,2012,Non-Executive Independent Director
3,NaN,NaN,NaN,NaN,NaN,NaN,Sunil Behari Mathur,74,2005,Non-Executive Independent Director
4,NaN,NaN,NaN,NaN,NaN,NaN,Shilabhadra Banerjee,70,2014,Non-Executive Independent Director
5,NaN,NaN,NaN,NaN,NaN,NaN,Arun Kumar Duggal,73,2014,Non-Executive Independent Director
6,NaN,NaN,NaN,NaN,NaN,NaN,Ajit Kumar Seth,67,2019,Additional Independent Director
7,NaN,NaN,NaN,NaN,NaN,NaN,David Robert Simpson,62,2017,Non-Executive Director - Representative of Tob...
8,NaN,NaN,NaN,NaN,NaN,NaN,John Pulinthanam,59,2018,Non-Executive Director - Representing the Gene...
9,NaN,NaN,NaN,NaN,NaN,NaN,Hemant Bhargava,59,2018,Additional Non-Executive Director
10,NaN,NaN,NaN,NaN,NaN,NaN,S. Sivakumar,58,2016,Group Head - Agri Business
11,NaN,NaN,NaN,NaN,NaN,NaN,Sanjay K. Singh,62,2017,Group Head - Paper & Packaging and Divisional ...
12,NaN,NaN,NaN,NaN,NaN,NaN,Rajendra Kumar Singhi,54,2018,"Executive Vice President, Secretary"
13,NaN,NaN,NaN,NaN,NaN,NaN,A. K. Rajput,63,0000,Senior Vice President - Corporate Affairs
14,NaN,NaN,NaN,NaN,NaN,NaN,Kannadiputhur Sundararaman Suresh,59,2009,General Counsel
15,NaN,NaN,NaN,NaN,NaN,NaN,Nakul Anand,62,2011,Executive Director
16,NaN,NaN,NaN,NaN,NaN,NaN,Chitranjan Dar,63,2015,"Group Head - LS&T, Central Projects, EHS and Q..."
17,NaN,NaN,NaN,NaN,NaN,NaN,B. Sumant,55,2018,"President - FMCG Businesses, Additional Wholet..."
18,NaN,NaN,NaN,NaN,NaN,NaN,Sanjiv Puri,56,2019,"Chairman of the Board, Managing Director, Exec..."
19,NaN,NaN,NaN,NaN,NaN,NaN,Rajiv Tandon,65,2016,"Chief Financial Officer, Executive Director"

In [173]:
final_data.to_csv('ITC_CompanyProfile.csv')